/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ApplicationMark: typeof import('./src/components/ApplicationMark.vue')['default']
    Banner: typeof import('./src/components/Banner.vue')['default']
    Dropdown: typeof import('./src/components/Dropdown.vue')['default']
    DropdownLink: typeof import('./src/components/DropdownLink.vue')['default']
    NavLink: typeof import('./src/components/NavLink.vue')['default']
    ResponsiveNavLink: typeof import('./src/components/ResponsiveNavLink.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
